Feature/complete
Quack-Survey/Back pull request #7
Opened 2023-09-16 04:48 UTC by ssssssjay

## 개요

- Complete(응답데이터) CRUD 작업사항
  
## PR타입

- [x] Feature : 기능 추가
- [ ] Fix: 버그 수정
- [ ] Style: 폴더 구조 및 파일명 변경, 단순 변수 수정 등
- [ ] Docs: 문서 수정
- [ ] Chore: 빌드 업무 및 패키지 업무 등

## 변경사항 및 기능설명

- `api/complete`
- GET `?userId=xxxx` : 생성자가 만든 모든 응답데이터 조회
- GET `?templateId=xxxx` : 설문조사의 모든 응답데이터 조회
- POST `?templateId=xxxx` : 설문조사 진입 시 상태가 0인 데이터 생성
- `api/complete/:id`
- GET : 특정 응답데이터 조회
- PATCH : req.body에 `{ responses: [ { formId: 'xxxx', response: ['xxxx'] } ] }` 데이터 요청
- DELETE : 특정 응답데이터 삭제

## 관련 이슈 넘버

#6

2023-09-16 05:10 UTC, Hun5LEE approved these changes

2023-09-16 05:10 UTC, Hun5LEE commented
확인완료! 고생하셨습니다 👍

2023-09-16 11:25 UTC, 0SCAR0421 requested changes
catch(err) 에서 res.sned로 err를 보내는데 대부분 db관련 에러인거 같습니다.

db관련 에러는 server쪽에서만 확인하고 클라이언트로는 노출하지 않는게 더 안전해 보입니다.

2023-09-16 11:25 UTC, 0SCAR0421 commented on models/complete.js
> +// prettier-ignore
prettier나 eslint는 사용하기로 합의된 사항이니 prettier-ignore나 eslint-disable-next-line는 지양하는 게 좋을거 같습니다

2023-09-16 11:25 UTC, 0SCAR0421 commented on routes/complete.js
> +        // ]
pr올리 실 때는 불필요한 주석은 다 지우는게 좋을거 같습니다!

2023-09-16 11:25 UTC, 0SCAR0421 commented on routes/complete.js
> +      const { userId, templateId } = req.query;
userid는 프론트엔드로 전달되지 않고 백엔드 미들웨어에서 처리됩니다.

최신화된 dev branch pull 받으신뒤 확인하시고 수정하는게 좋을거 같습니다!

2023-09-16 11:25 UTC, 0SCAR0421 commented on routes/complete.js
> +  .get(async (req, res) => {
GET complete/ 요청에 query data가 없는 경우에 대한 예외처리가 없습니다.

반대로 query data로 userId와 templateId가 두개 다 들어오면 userId와 templateId에 해당되는 값 두개가 모두 리턴되는 건가요?

2023-09-16 17:22 UTC, ssssssjay commented on routes/complete.js
> +        // ]
넵 반영하고 push 하겠습니다🫡

2023-09-16 17:23 UTC, ssssssjay commented on models/complete.js
> +// prettier-ignore
넵 반영하고 push 하겠습니다🫡

2023-09-16 17:23 UTC, ssssssjay commented
> catch(err) 에서 res.sned로 err를 보내는데 대부분 db관련 에러인거 같습니다.
> 
> db관련 에러는 server쪽에서만 확인하고 클라이언트로는 노출하지 않는게 더 안전해 보입니다.

넵 반영하고 push 하겠습니다🫡

2023-09-17 05:43 UTC, ssssssjay commented on routes/complete.js
> +  .get(async (req, res) => {
현재로는 둘다 들어오며 유저가 먼저 전송될것같네요ㅠㅠ 한번 처리해보고 다시 푸쉬해볼게요

2023-09-17 05:44 UTC, ssssssjay commented on routes/complete.js
> +      const { userId, templateId } = req.query;
확인해보고 올려보겠습니다...!

2023-09-18 06:33 UTC, nanhimang approved these changes
고생많으셨슴니다!!! 구현하신 기능목록 살펴봤는데,
지금까지 하신 부분이 유저가 설문을 완료 후 데이터가 POST 되는 시점의 API이신거죠?

2023-09-18 06:43 UTC, ssssssjay commented
> 고생많으셨슴니다!!! 구현하신 기능목록 살펴봤는데, 지금까지 하신 부분이 유저가 설문을 완료 후 데이터가 POST 되는 시점의 API이신거죠?

네네, 그 부분도 있고 기존에 저장되어있는 데이터 조회도 있는거에요!

2023-09-18 07:53 UTC, 0SCAR0421 approved these changes
고생하셨습니다!! 👏

2023-09-18 07:53 UTC, merged